// ============================================================
// HAC PLUGIN — build.cjs
// Assembles all modular source files into the final ui.html
// that Figma requires as a single file.
//
// Usage:  node src/plugin/build.cjs
// Or via: npm run bundle:ui
// ============================================================

const fs   = require('fs');
const path = require('path');

const BASE = path.join(__dirname);
const OUT  = path.join(BASE, 'ui.html');

// ── Helpers ──────────────────────────────────────────────────
function read(relPath) {
  const abs = path.join(BASE, relPath);
  if (!fs.existsSync(abs)) {
    console.warn(`⚠  Missing: ${relPath}`);
    return `/* MISSING: ${relPath} */`;
  }
  return fs.readFileSync(abs, 'utf8');
}

// ── Load source parts ─────────────────────────────────────────
const tailwindCSS = read('styles/tailwind-compiled.css');
const css         = read('styles/plugin.css');
const modCore    = read('modules/core.js');
const modA11yConstantsGenerated = read('refs/_a11y-constants.generated.js');
// Frames de instrução (2026-09-08) — imagens PNG (base64) capturadas via
// CI da lib "Design Acessível", usadas como coluna de instrução fixa na
// Ficha de Handoff (ver refs/fetch-instruction-frames.cjs e
// refs/build-skeleton.cjs). Gerado, pode ainda não existir num checkout
// limpo antes do primeiro `npm run bundle:refs` — read() já trata
// arquivo ausente com um comentário placeholder, sem quebrar o build.
const modInstructionFramesGenerated = read('refs/_instruction-frames.generated.js');
// Conteúdo rico da coluna de instrução da Ficha (título, texto explicativo,
// passos numerados, seção de Assets) — mesmo dado consumido pelo backend
// via ficha-instruction-content.json (import estático em code.js), exposto
// aqui pro frontend como FICHA_INSTRUCTION_CONTENT_UI (ver
// refs/build-ficha-instruction-constants.cjs). Precisa vir ANTES de
// accessibility.js e onboarding.js — os dois podem consumir essa constante
// (onboarding.js enriquece os passos de Tabulação/Leitor de Tela com ela).
const modFichaInstructionGenerated = read('refs/_ficha-instruction-content.generated.js');
const modA11y    = read('modules/accessibility.js');
// Ordem de Tabulação e Trilha de Swipe (2026-09-09) — extraídos de
// accessibility.js pra reduzir o maior arquivo do projeto. tab-order.js
// precisa vir ANTES de handoff-ficha.js: a Ficha consome
// _currentTabOrderItems. swipe-path.js referencia globalmente
// cancelTabOrderReview()/window._tabOrderCaptureMode (tab-order.js), então
// também precisa vir depois dele.
const modTabOrder  = read('modules/tab-order.js');
const modSwipePath = read('modules/swipe-path.js');
const modFicha   = read('modules/handoff-ficha.js');
const modOnboard = read('modules/onboarding.js');
const modMsgs    = read('modules/messages.js');

// ── Load DSC reference skeleton (só a lib web-angular-react —
// keys/names dos componentes, usado só pra resolver componentKey →
// containingFrame → categoria de a11y). Regenerar via:
// node src/plugin/refs/build-skeleton.cjs
const skeletonPath = path.join(BASE, 'refs', '_skeleton.json');
let refSkeletonJSON = 'null';
if (fs.existsSync(skeletonPath)) {
  const raw = fs.readFileSync(skeletonPath, 'utf8');
  const parsed = JSON.parse(raw);
  refSkeletonJSON = JSON.stringify(parsed);

  // Sanity-check against characters that break the JS string literal —
  // Figma wraps ui.html in: U+2028 LINE SEP, U+2029 PARA SEP.
  const u2028 = String.fromCharCode(0x2028);
  const u2029 = String.fromCharCode(0x2029);
  if (refSkeletonJSON.indexOf(u2028) >= 0 || refSkeletonJSON.indexOf(u2029) >= 0) {
    throw new Error('⛔  _skeleton.json contains U+2028/U+2029 — regenerate via build-skeleton.cjs');
  }
} else {
  console.warn('⚠  refs/_skeleton.json not found — run: node src/plugin/refs/build-skeleton.cjs');
}

// ── Load view partials ────────────────────────────────────────
const viewHome    = read('views/home.html');
const viewSpecs   = read('views/specifications.html');
const modalsShared = read('views/modals.html');

// ── Assemble ──────────────────────────────────────────────────
const html = `<!doctype html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <script src="https://unpkg.com/lucide@latest" defer></script>
  <script>
    // Shim síncrono: garante que window.lucide existe antes dos módulos rodarem
    // (lucide é defer — pode não ter carregado ainda ao executar os módulos).
    // Quando o script defer carregar, substitui o shim e dispara _refreshIcons.
    if (typeof window.lucide === 'undefined') {
      window.lucide = { createIcons: function () {} };
    }
    document.querySelector('script[src*="lucide"]')?.addEventListener('load', function() {
      if (window._refreshIcons) window._refreshIcons();
    });
  </script>
  <script>
    // DSC reference skeleton — generated by refs/build-skeleton.cjs.
    // Contém só a lib web-angular-react (keys/names de componente) — usado
    // pra resolver componentKey → containingFrame → categoria de a11y.
    window.__HAC_REF_SKELETON__ = ${refSkeletonJSON};
  </script>
  <style>
${tailwindCSS}
${css}
  </style>
</head>

<body class="h-screen flex flex-col overflow-hidden bg-light-bg text-slate-900 dark:bg-dark-bg dark:text-dark-text">
  <header
    class="relative flex items-center justify-between px-4 py-2 border-b border-light-line dark:border-dark-line shrink-0 bg-light-surface dark:bg-dark-bg z-50">
    <div id="header-home" class="flex items-center justify-between w-full">
      <button type="button" onclick="openAboutHacModal()" title="Sobre o hac" aria-label="Sobre o hac — versão, vertical responsável e desenvolvimento"
        class="flex items-center gap-2 rounded-2xl -mx-1 px-1 py-1 hover:bg-light-line dark:hover:bg-dark-surface transition-colors cursor-pointer">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 205.51265 46.553631" class="h-5 w-auto shrink-0" aria-label="CAIXA">
          <g transform="translate(-284.78446,-475.51214)">
            <g transform="matrix(1.25,0,0,-1.25,15.493106,1024.9702)">
              <g transform="scale(0.24,0.24)">
                <path d="m 1107.19,1780.04 -17.74,-44.21 24.55,0 -6.73,44.39 -0.08,-0.18 z m -93.98,-101.49 72.77,149.83 55.02,0 30.68,-149.83 -48.3,0 -3.56,19.97 -46.86,0 -10.78,-19.97 -48.97,0 z m 181.34,0 21.08,149.83 48.67,0 -21.07,-149.83 -48.68,0 z m 323.71,101.67 -17.81,-44.39 24.54,0 -6.73,44.39 z m -94.06,-101.67 72.78,149.83 55.01,0 30.69,-149.83 -48.31,0 -3.55,19.97 -46.87,0 -10.78,-19.97 -48.97,0" style="fill:#005ca9;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1316.6,1748.61 60.99,0 41.79,-69.21 -61,0 -41.78,69.21" style="fill:#005ca9;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1322.94,1759.24 63.04,0 54.75,68.92 -63.04,0 -54.75,-68.92" style="fill:#f39200;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1259.91,1678.98 63.03,0 54.75,69.76 -63.04,0 -54.74,-69.76" style="fill:#f39200;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1282.64,1829 58.83,0 40.31,-69.76 -58.84,0 -40.3,69.76" style="fill:#005ca9;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1014.65,1823.02 -4.68,-44.07 c -17.939,24.75 -59.517,7.67 -62.782,-23.16 -4.149,-39.13 35.867,-48.25 57.642,-25.21 l -4.69,-44.17 c -6.499,-3.19 -12.855,-5.67 -19.128,-7.34 -6.239,-1.68 -12.492,-2.57 -18.696,-2.7 -7.8,-0.17 -14.867,0.65 -21.234,2.44 -6.367,1.76 -12.129,4.56 -17.227,8.34 -9.832,7.19 -16.941,16.33 -21.32,27.45 -4.379,11.16 -5.82,23.75 -4.328,37.82 1.203,11.31 4.051,21.62 8.59,30.97 4.5,9.34 10.734,17.84 18.672,25.54 7.504,7.34 15.676,12.88 24.519,16.64 8.809,3.73 18.422,5.72 28.813,5.94 6.207,0.13 12.297,-0.49 18.207,-1.92 5.942,-1.42 11.802,-3.64 17.642,-6.57" style="fill:#005ca9;fill-opacity:1;fill-rule:evenodd;stroke:none" />
              </g>
            </g>
          </g>
        </svg>
        <span class="text-slate-200 dark:text-slate-700 font-bold text-sm">|</span>
        <i data-lucide="person-standing" class="w-4 h-4 text-[#0070af]" aria-hidden="true"></i>
        <h1 class="font-bold text-[#1E293B] dark:text-white text-[12px] tracking-[0.15em] uppercase">
          HAC
        </h1>
      </button>
      <div class="flex items-center gap-2 shrink-0">
        <button id="btn-zoom-out" onclick="ensureExpanded(); zoomOut()" title="Diminuir escala" aria-label="Diminuir escala da interface"
          class="hidden p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="zoom-out" class="w-5 h-5" aria-hidden="true"></i>
        </button>
        <button id="btn-zoom-in" onclick="ensureExpanded(); zoomIn()" title="Aumentar escala" aria-label="Aumentar escala da interface"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="zoom-in" class="w-5 h-5" aria-hidden="true"></i>
        </button>
        <button onclick="toggleTheme()" title="Alternar tema" aria-label="Alternar tema claro/escuro"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="sun" class="sun-icon w-5 h-5" aria-hidden="true"></i>
          <i data-lucide="moon" class="moon-icon w-5 h-5 hidden" aria-hidden="true"></i>
        </button>
        <button onclick="toggleCollapse()" id="btn-collapse" aria-label="Minimizar plugin"
          title="Minimizar — clique no ícone para expandir novamente"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="minimize-2" class="w-4 h-4" aria-hidden="true"></i>
        </button>
      </div>
    </div>

  </header>

  <!-- Barra de captura (Ordem de Tabulação / Trilha de Swipe, 2026-09-04-w,
       redesenhada 2026-09-15) — IRMÃ do <header> (não filha), abaixo dele.
       #header-home (logo CAIXA, zoom, tema, minimizar) é ESCONDIDO durante
       a captura (_a11yCaptureMiniBarEnter, core.js) — esta barra assume o
       papel de "header" nesse modo. Ordem: linha de contador+ações PRIMEIRO
       (sempre visível, faz as vezes de header — contém o chevron de
       recolher/expandir), bloco de instruções DEPOIS, abaixo dela, visível
       só quando expandido (pedido do usuário: "o header que eu queria era
       com o contador, o botão para expandir para as instruções e cancelar
       e concluir" — recolhido = só esta linha, mesma altura de
       CAPTURE_MINI_H; expandido = esta linha + o bloco de instruções
       abaixo). Nunca sai do modo de captura em nenhum dos dois estados —
       a escuta de cliques no canvas continua ativa o tempo todo. -->
  <!-- shrink-0 é obrigatório: o body é 'h-screen flex flex-col', e num
       container flex o filho encolhe por padrão quando falta espaço. Com a
       janela ainda na altura ANTERIOR (menor) no instante da medição, a
       barra seria comprimida e getBoundingClientRect() devolveria a altura
       comprimida — a medição se auto-limitaria e a janela nunca cresceria
       o bastante. Com shrink-0 ela sempre reporta a altura natural do
       conteúdo, que é o que _a11yCaptureBarMeasuredHeight (core.js) usa. -->
  <div id="a11y-capture-mini-bar" class="hidden flex-col w-full shrink-0">
    <div class="flex items-center justify-between w-full gap-2 px-4 py-2.5 shrink-0">
      <div class="flex items-center gap-2 min-w-0">
        <span class="w-2 h-2 rounded-full bg-[#0891B2] animate-pulse shrink-0" aria-hidden="true"></span>
        <span id="a11y-capture-mini-bar-count" class="text-[11px] font-bold text-slate-700 dark:text-white truncate">
          0 pontos marcados
        </span>
      </div>
      <div class="flex items-center gap-2 shrink-0">
        <!-- Alterna o bloco de instruções abaixo entre visível (padrão) e
             recolhido — feature lida de window._a11yCaptureMiniBarFeature
             ('tabOrder'|'swipePath'), convertida pra chave do conteúdo
             ('tabulacao'|'swipe') por _a11yCaptureBarToggleInstructions
             (core.js). Ícone/título trocam conforme o estado atual. -->
        <!-- tooltip-bottom em toda a barra: ela fica no topo da janela, e o
             tooltip padrão (acima) seria cortado. O texto de cada um é
             reescrito em runtime por _a11yCaptureBarSyncTooltips (core.js)
             conforme o estado (recolhido/expandido) e a feature ativa
             (itens de Tabulação vs. pontos de Swipe) — os valores abaixo
             são só o estado inicial. -->
        <button type="button" id="a11y-capture-mini-bar-help" onclick="_a11yCaptureBarToggleInstructions()"
          data-tooltip="Recolher as instruções e liberar espaço no canvas" class="tooltip-left w-7 h-7 flex items-center justify-center text-slate-400 dark:text-dark-muted hover:text-cyan-600 dark:hover:text-cyan-400 hover:bg-light-line dark:hover:bg-dark-surface rounded-xl transition-colors shrink-0"
          aria-label="Recolher instruções">
          <i data-lucide="chevron-up" id="a11y-capture-mini-bar-help-icon" class="w-4 h-4"></i>
        </button>
        <button type="button" id="a11y-capture-mini-bar-cancel" onclick="_a11yCaptureMiniBarCancel()"
          data-tooltip="Sair sem documentar nada — o que você marcou é descartado" class="tooltip-bottom px-2.5 py-1.5 text-[10.5px] font-bold text-slate-500 dark:text-dark-muted hover:bg-light-line dark:hover:bg-dark-surface rounded-xl transition-colors"
          aria-label="Cancelar seleção e descartar o que foi marcado">
          Cancelar
        </button>
        <button type="button" id="a11y-capture-mini-bar-finish" onclick="_a11yCaptureMiniBarFinish()"
          data-tooltip="Terminar a marcação e revisar a lista antes de aplicar" class="tooltip-left px-3 py-1.5 text-[10.5px] font-bold text-white bg-[#0891B2] hover:bg-cyan-700 rounded-xl transition-colors shadow-lg shadow-cyan-500/20"
          aria-label="Concluir seleção e revisar a lista">
          Concluir seleção
        </button>
      </div>
    </div>
    <!-- SEM teto de altura e SEM overflow (2026-09-15, pedido do usuário:
         "não quero rolagem nessa etapa"): o bloco cresce até o tamanho
         natural do conteúdo, e a janela do Figma é redimensionada pra
         caber exatamente isso (_a11yCaptureBarApplyInstructionsVisibility,
         core.js, mede o scrollHeight real). Um max-h aqui voltaria a
         cortar o texto e criar a barra de rolagem. -->
    <div id="a11y-capture-bar-instructions" class="w-full px-4 pb-3 pt-1 space-y-2.5 border-t border-gray-100 dark:border-dark-line">
      <h3 id="a11y-capture-bar-instructions-title" class="font-bold text-[13px] text-slate-800 dark:text-white flex items-center gap-1.5 mt-2">
        <i data-lucide="book-open-check" class="w-3.5 h-3.5 text-[#0891B2]" aria-hidden="true"></i> <span id="a11y-capture-bar-instructions-title-text">Ordem de Tabulação</span>
      </h3>
      <div class="rounded-dsc-medium border border-gray-100 dark:border-dark-line p-3">
        <h4 id="a11y-capture-bar-instructions-heading" class="font-bold text-[11px] text-slate-800 dark:text-white mb-1.5">Instruções sobre o tipo de documentação</h4>
        <p id="a11y-capture-bar-instructions-body" class="text-dsc-label-tiny normal-case tracking-normal text-slate-600 dark:text-dark-muted leading-relaxed"></p>
      </div>
      <div class="rounded-dsc-medium border border-gray-100 dark:border-dark-line p-3">
        <h4 id="a11y-capture-bar-steps-heading" class="font-bold text-[11px] text-slate-800 dark:text-white mb-1.5">Como fazer</h4>
        <ol id="a11y-capture-bar-steps" class="text-dsc-label-tiny normal-case tracking-normal text-slate-600 dark:text-dark-muted leading-relaxed list-decimal list-inside space-y-2"></ol>
      </div>
    </div>
  </div>

  <div class="flex-1 overflow-hidden relative min-h-0">
${viewHome}
${viewSpecs}
${modalsShared}
  </div>

  <!-- Botão "Voltar ao topo" (2026-09-11, bug real corrigido) — CSS
       (styles/plugin.css) e as 4 funções JS que já o referenciam
       (scrollToTop/handleScroll/navigate/toggleCollapse, core.js) sempre
       existiram, mas o <button> em si nunca foi incluído aqui neste
       build.cjs — perdido na extração do hac a partir do Handex
       (commit e16a67c, 2026-08-25): CSS e JS foram copiados, o markup do
       elemento não. Sem ele no DOM, scrollToTop() virava no-op silencioso
       (guard 'if (btnTop)' em todo call-site). Fixed no body (fora de
       qualquer .view), pra funcionar em qualquer tela sem precisar
       duplicar por view — mesmo padrão do Handex original. -->
  <button id="btn-top" onclick="scrollToTop()" title="Voltar ao topo" aria-label="Voltar ao topo"
    class="fixed bottom-6 right-6 w-10 h-10 rounded-full flex items-center justify-center opacity-0 pointer-events-none translate-y-10 z-[100] transition-colors duration-200">
    <i data-lucide="chevron-up" class="w-5 h-5"></i>
  </button>

  <!--
    Plugin runtime — concatenado em um único <script> para que todos os
    módulos compartilhem o mesmo escopo. A separação em arquivos-fonte é
    puramente organizacional; o resultado em runtime é idêntico ao monolito.
  -->
  <script>
// ============================================================
// MODULE: core.js
// ============================================================
${modCore}

// ============================================================
// MODULE: messages.js
// ============================================================
${modMsgs}

// ============================================================
// GENERATED: refs/_a11y-constants.generated.js
// (fonte de verdade de A11Y_COMPONENT_PROPERTIES_GENERATED e
// A11Y_MOBILE_LINK_COMPONENT_OPTIONS_GENERATED — precisa vir ANTES de
// accessibility.js, que referencia essas constantes. Regenerar via:
// npm run refs:a11y-constants)
// ============================================================
${modA11yConstantsGenerated}

// ============================================================
// GENERATED: refs/_instruction-frames.generated.js
// (window.__HAC_INSTRUCTION_FRAMES__ — PNGs, base64, da lib "Design
// Acessível", consumidos pela Ficha de Handoff. Regenerar via:
// npm run bundle:refs, depois de rodar
// FIGMA_TOKEN=xxx node src/plugin/refs/fetch-instruction-frames.cjs)
// ============================================================
${modInstructionFramesGenerated}

// ============================================================
// GENERATED: refs/_ficha-instruction-content.generated.js
// (FICHA_INSTRUCTION_CONTENT_UI — conteúdo rico da coluna de instrução da
// Ficha, consumido por onboarding.js. Regenerar via:
// npm run refs:ficha-instruction)
// ============================================================
${modFichaInstructionGenerated}

// ============================================================
// MODULE: accessibility.js
// ============================================================
${modA11y}

// ============================================================
// MODULE: tab-order.js
// (Ordem de Tabulação — extraído de accessibility.js em 2026-09-09.
// Precisa vir ANTES de handoff-ficha.js: a Ficha consome
// _currentTabOrderItems.)
// ============================================================
${modTabOrder}

// ============================================================
// MODULE: swipe-path.js
// (Trilha de Swipe — extraído de accessibility.js em 2026-09-09.
// Precisa vir DEPOIS de tab-order.js: referencia globalmente
// cancelTabOrderReview()/window._tabOrderCaptureMode.)
// ============================================================
${modSwipePath}

// ============================================================
// MODULE: handoff-ficha.js
// (Ficha de Handoff — módulo apartado, ver comentário de topo do arquivo.
// Precisa vir DEPOIS de accessibility.js/tab-order.js: referencia
// A11Y_CATEGORIES, switchA11yWorkspaceTab, a11yAreas/a11ySpecs,
// _currentTabOrderItems, saveToStorage etc.)
// ============================================================
${modFicha}

// ============================================================
// MODULE: onboarding.js
// ============================================================
${modOnboard}
  </script>

  <script>
    window.addEventListener('load', () => {
      if (typeof lucide !== 'undefined') lucide.createIcons();
    });
  </script>

  <div id="toast-container" role="status" aria-live="polite" aria-atomic="true"></div>
  <div id="resize-handle"></div>

</body>
</html>
`;

fs.writeFileSync(OUT, html, 'utf8');
console.log(`✅ ui.html assembled (${(html.length / 1024).toFixed(1)} KB)`);
console.log(`   Source: ${BASE}`);
console.log(`   Output: ${OUT}`);
