// ============================================================
// HAC PLUGIN — build.cjs
// Assembles all modular source files into the final ui.html
// that Figma requires as a single file.
//
// Usage:  node src/plugin/build.cjs
// Or via: npm run bundle:ui
// ============================================================

const fs   = require('fs');
const path = require('path');

const BASE = path.join(__dirname);
const OUT  = path.join(BASE, 'ui.html');

// ── Helpers ──────────────────────────────────────────────────
function read(relPath) {
  const abs = path.join(BASE, relPath);
  if (!fs.existsSync(abs)) {
    console.warn(`⚠  Missing: ${relPath}`);
    return `/* MISSING: ${relPath} */`;
  }
  return fs.readFileSync(abs, 'utf8');
}

// ── Load source parts ─────────────────────────────────────────
const tailwindCSS = read('styles/tailwind-compiled.css');
const css         = read('styles/plugin.css');
const modCore    = read('modules/core.js');
const modA11y    = read('modules/accessibility.js');
const modOnboard = read('modules/onboarding.js');
const modMsgs    = read('modules/messages.js');

// ── Load DSC reference skeleton (só a lib web-angular-react —
// keys/names dos componentes, usado só pra resolver componentKey →
// containingFrame → categoria de a11y). Regenerar via:
// node src/plugin/refs/build-skeleton.cjs
const skeletonPath = path.join(BASE, 'refs', '_skeleton.json');
let refSkeletonJSON = 'null';
if (fs.existsSync(skeletonPath)) {
  const raw = fs.readFileSync(skeletonPath, 'utf8');
  const parsed = JSON.parse(raw);
  refSkeletonJSON = JSON.stringify(parsed);

  // Sanity-check against characters that break the JS string literal —
  // Figma wraps ui.html in: U+2028 LINE SEP, U+2029 PARA SEP.
  const u2028 = String.fromCharCode(0x2028);
  const u2029 = String.fromCharCode(0x2029);
  if (refSkeletonJSON.indexOf(u2028) >= 0 || refSkeletonJSON.indexOf(u2029) >= 0) {
    throw new Error('⛔  _skeleton.json contains U+2028/U+2029 — regenerate via build-skeleton.cjs');
  }
} else {
  console.warn('⚠  refs/_skeleton.json not found — run: node src/plugin/refs/build-skeleton.cjs');
}

// ── Load view partials ────────────────────────────────────────
const viewHome    = read('views/home.html');
const viewSpecs   = read('views/specifications.html');
const modalsShared = read('views/modals.html');

// ── Assemble ──────────────────────────────────────────────────
const html = `<!doctype html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <script src="https://unpkg.com/lucide@latest" defer></script>
  <script>
    // Shim síncrono: garante que window.lucide existe antes dos módulos rodarem
    // (lucide é defer — pode não ter carregado ainda ao executar os módulos).
    // Quando o script defer carregar, substitui o shim e dispara _refreshIcons.
    if (typeof window.lucide === 'undefined') {
      window.lucide = { createIcons: function () {} };
    }
    document.querySelector('script[src*="lucide"]')?.addEventListener('load', function() {
      if (window._refreshIcons) window._refreshIcons();
    });
  </script>
  <script>
    // DSC reference skeleton — generated by refs/build-skeleton.cjs.
    // Contém só a lib web-angular-react (keys/names de componente) — usado
    // pra resolver componentKey → containingFrame → categoria de a11y.
    window.__HAC_REF_SKELETON__ = ${refSkeletonJSON};
  </script>
  <style>
${tailwindCSS}
${css}
  </style>
</head>

<body class="h-screen flex flex-col overflow-hidden bg-light-bg text-slate-900 dark:bg-dark-bg dark:text-dark-text">
  <header
    class="relative flex items-center justify-between px-4 py-2 border-b border-light-line dark:border-dark-line shrink-0 bg-light-surface dark:bg-dark-bg z-50">
    <div id="header-home" class="flex items-center justify-between w-full">
      <div class="flex items-center gap-2">
        <i data-lucide="accessibility" class="w-5 h-5 text-[#0070af]" aria-hidden="true"></i>
        <h1 class="font-bold text-[#1E293B] dark:text-white text-[12px] tracking-[0.15em] uppercase">
          HAC
        </h1>
        <span id="version-badge" class="ml-2 px-1.5 py-0.5 bg-blue-100 dark:bg-blue-900/40 text-blue-600 dark:text-blue-400 text-[10px] font-bold rounded flex items-center justify-center">v0.1.0-beta.1</span>
      </div>
      <div class="flex items-center gap-2 shrink-0">
        <button id="btn-zoom-out" onclick="ensureExpanded(); zoomOut()" title="Diminuir escala" aria-label="Diminuir escala da interface"
          class="hidden p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="zoom-out" class="w-5 h-5" aria-hidden="true"></i>
        </button>
        <button id="btn-zoom-in" onclick="ensureExpanded(); zoomIn()" title="Aumentar escala" aria-label="Aumentar escala da interface"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="zoom-in" class="w-5 h-5" aria-hidden="true"></i>
        </button>
        <button onclick="toggleTheme()" title="Alternar tema" aria-label="Alternar tema claro/escuro"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="sun" class="sun-icon w-5 h-5" aria-hidden="true"></i>
          <i data-lucide="moon" class="moon-icon w-5 h-5 hidden" aria-hidden="true"></i>
        </button>
        <button onclick="toggleCollapse()" id="btn-collapse" aria-label="Minimizar plugin"
          title="Minimizar — clique no ícone para expandir novamente"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="minimize-2" class="w-4 h-4" aria-hidden="true"></i>
        </button>
      </div>
    </div>
  </header>

  <div class="flex-1 overflow-hidden relative min-h-0">
${viewHome}
${viewSpecs}
${modalsShared}
  </div>

  <!-- SIGNATURE FOOTER -->
  <footer id="footer-signature" class="pb-2 pt-1 text-center shrink-0 bg-light-surface dark:bg-dark-bg border-t border-light-line dark:border-dark-line">
    <p class="text-[9px] text-gray-400 dark:text-dark-muted font-bold tracking-wider uppercase">
      Desenvolvido por Fóton
    </p>
  </footer>

  <!--
    Plugin runtime — concatenado em um único <script> para que todos os
    módulos compartilhem o mesmo escopo. A separação em arquivos-fonte é
    puramente organizacional; o resultado em runtime é idêntico ao monolito.
  -->
  <script>
// ============================================================
// MODULE: core.js
// ============================================================
${modCore}

// ============================================================
// MODULE: messages.js
// ============================================================
${modMsgs}

// ============================================================
// MODULE: accessibility.js
// ============================================================
${modA11y}

// ============================================================
// MODULE: onboarding.js
// ============================================================
${modOnboard}
  </script>

  <script>
    window.addEventListener('load', () => {
      if (typeof lucide !== 'undefined') lucide.createIcons();
    });
  </script>

  <div id="toast-container"></div>
  <div id="resize-handle"></div>

</body>
</html>
`;

fs.writeFileSync(OUT, html, 'utf8');
console.log(`✅ ui.html assembled (${(html.length / 1024).toFixed(1)} KB)`);
console.log(`   Source: ${BASE}`);
console.log(`   Output: ${OUT}`);
