// ============================================================
// HAC PLUGIN — build.cjs
// Assembles all modular source files into the final ui.html
// that Figma requires as a single file.
//
// Usage:  node src/plugin/build.cjs
// Or via: npm run bundle:ui
// ============================================================

const fs   = require('fs');
const path = require('path');

const BASE = path.join(__dirname);
const OUT  = path.join(BASE, 'ui.html');

// ── Helpers ──────────────────────────────────────────────────
function read(relPath) {
  const abs = path.join(BASE, relPath);
  if (!fs.existsSync(abs)) {
    console.warn(`⚠  Missing: ${relPath}`);
    return `/* MISSING: ${relPath} */`;
  }
  return fs.readFileSync(abs, 'utf8');
}

// ── Load source parts ─────────────────────────────────────────
const tailwindCSS = read('styles/tailwind-compiled.css');
const css         = read('styles/plugin.css');
const modCore    = read('modules/core.js');
const modA11yConstantsGenerated = read('refs/_a11y-constants.generated.js');
const modA11y    = read('modules/accessibility.js');
const modOnboard = read('modules/onboarding.js');
const modMsgs    = read('modules/messages.js');

// ── Load DSC reference skeleton (só a lib web-angular-react —
// keys/names dos componentes, usado só pra resolver componentKey →
// containingFrame → categoria de a11y). Regenerar via:
// node src/plugin/refs/build-skeleton.cjs
const skeletonPath = path.join(BASE, 'refs', '_skeleton.json');
let refSkeletonJSON = 'null';
if (fs.existsSync(skeletonPath)) {
  const raw = fs.readFileSync(skeletonPath, 'utf8');
  const parsed = JSON.parse(raw);
  refSkeletonJSON = JSON.stringify(parsed);

  // Sanity-check against characters that break the JS string literal —
  // Figma wraps ui.html in: U+2028 LINE SEP, U+2029 PARA SEP.
  const u2028 = String.fromCharCode(0x2028);
  const u2029 = String.fromCharCode(0x2029);
  if (refSkeletonJSON.indexOf(u2028) >= 0 || refSkeletonJSON.indexOf(u2029) >= 0) {
    throw new Error('⛔  _skeleton.json contains U+2028/U+2029 — regenerate via build-skeleton.cjs');
  }
} else {
  console.warn('⚠  refs/_skeleton.json not found — run: node src/plugin/refs/build-skeleton.cjs');
}

// ── Load view partials ────────────────────────────────────────
const viewHome    = read('views/home.html');
const viewSpecs   = read('views/specifications.html');
const modalsShared = read('views/modals.html');

// ── Assemble ──────────────────────────────────────────────────
const html = `<!doctype html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <script src="https://unpkg.com/lucide@latest" defer></script>
  <script>
    // Shim síncrono: garante que window.lucide existe antes dos módulos rodarem
    // (lucide é defer — pode não ter carregado ainda ao executar os módulos).
    // Quando o script defer carregar, substitui o shim e dispara _refreshIcons.
    if (typeof window.lucide === 'undefined') {
      window.lucide = { createIcons: function () {} };
    }
    document.querySelector('script[src*="lucide"]')?.addEventListener('load', function() {
      if (window._refreshIcons) window._refreshIcons();
    });
  </script>
  <script>
    // DSC reference skeleton — generated by refs/build-skeleton.cjs.
    // Contém só a lib web-angular-react (keys/names de componente) — usado
    // pra resolver componentKey → containingFrame → categoria de a11y.
    window.__HAC_REF_SKELETON__ = ${refSkeletonJSON};
  </script>
  <style>
${tailwindCSS}
${css}
  </style>
</head>

<body class="h-screen flex flex-col overflow-hidden bg-light-bg text-slate-900 dark:bg-dark-bg dark:text-dark-text">
  <header
    class="relative flex items-center justify-between px-4 py-2 border-b border-light-line dark:border-dark-line shrink-0 bg-light-surface dark:bg-dark-bg z-50">
    <div id="header-home" class="flex items-center justify-between w-full">
      <button type="button" onclick="openAboutHacModal()" title="Sobre o hac" aria-label="Sobre o hac — versão, vertical responsável e desenvolvimento"
        class="flex items-center gap-2 rounded-2xl -mx-1 px-1 py-1 hover:bg-light-line dark:hover:bg-dark-surface transition-colors cursor-pointer">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 205.51265 46.553631" class="h-5 w-auto shrink-0" aria-label="CAIXA">
          <g transform="translate(-284.78446,-475.51214)">
            <g transform="matrix(1.25,0,0,-1.25,15.493106,1024.9702)">
              <g transform="scale(0.24,0.24)">
                <path d="m 1107.19,1780.04 -17.74,-44.21 24.55,0 -6.73,44.39 -0.08,-0.18 z m -93.98,-101.49 72.77,149.83 55.02,0 30.68,-149.83 -48.3,0 -3.56,19.97 -46.86,0 -10.78,-19.97 -48.97,0 z m 181.34,0 21.08,149.83 48.67,0 -21.07,-149.83 -48.68,0 z m 323.71,101.67 -17.81,-44.39 24.54,0 -6.73,44.39 z m -94.06,-101.67 72.78,149.83 55.01,0 30.69,-149.83 -48.31,0 -3.55,19.97 -46.87,0 -10.78,-19.97 -48.97,0" style="fill:#005ca9;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1316.6,1748.61 60.99,0 41.79,-69.21 -61,0 -41.78,69.21" style="fill:#005ca9;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1322.94,1759.24 63.04,0 54.75,68.92 -63.04,0 -54.75,-68.92" style="fill:#f39200;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1259.91,1678.98 63.03,0 54.75,69.76 -63.04,0 -54.74,-69.76" style="fill:#f39200;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1282.64,1829 58.83,0 40.31,-69.76 -58.84,0 -40.3,69.76" style="fill:#005ca9;fill-opacity:1;fill-rule:evenodd;stroke:none" />
                <path d="m 1014.65,1823.02 -4.68,-44.07 c -17.939,24.75 -59.517,7.67 -62.782,-23.16 -4.149,-39.13 35.867,-48.25 57.642,-25.21 l -4.69,-44.17 c -6.499,-3.19 -12.855,-5.67 -19.128,-7.34 -6.239,-1.68 -12.492,-2.57 -18.696,-2.7 -7.8,-0.17 -14.867,0.65 -21.234,2.44 -6.367,1.76 -12.129,4.56 -17.227,8.34 -9.832,7.19 -16.941,16.33 -21.32,27.45 -4.379,11.16 -5.82,23.75 -4.328,37.82 1.203,11.31 4.051,21.62 8.59,30.97 4.5,9.34 10.734,17.84 18.672,25.54 7.504,7.34 15.676,12.88 24.519,16.64 8.809,3.73 18.422,5.72 28.813,5.94 6.207,0.13 12.297,-0.49 18.207,-1.92 5.942,-1.42 11.802,-3.64 17.642,-6.57" style="fill:#005ca9;fill-opacity:1;fill-rule:evenodd;stroke:none" />
              </g>
            </g>
          </g>
        </svg>
        <span class="text-slate-200 dark:text-slate-700 font-bold text-sm">|</span>
        <i data-lucide="person-standing" class="w-4 h-4 text-[#0070af]" aria-hidden="true"></i>
        <h1 class="font-bold text-[#1E293B] dark:text-white text-[12px] tracking-[0.15em] uppercase">
          HAC
        </h1>
      </button>
      <div class="flex items-center gap-2 shrink-0">
        <button id="btn-zoom-out" onclick="ensureExpanded(); zoomOut()" title="Diminuir escala" aria-label="Diminuir escala da interface"
          class="hidden p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="zoom-out" class="w-5 h-5" aria-hidden="true"></i>
        </button>
        <button id="btn-zoom-in" onclick="ensureExpanded(); zoomIn()" title="Aumentar escala" aria-label="Aumentar escala da interface"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="zoom-in" class="w-5 h-5" aria-hidden="true"></i>
        </button>
        <button onclick="toggleTheme()" title="Alternar tema" aria-label="Alternar tema claro/escuro"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="sun" class="sun-icon w-5 h-5" aria-hidden="true"></i>
          <i data-lucide="moon" class="moon-icon w-5 h-5 hidden" aria-hidden="true"></i>
        </button>
        <button onclick="toggleCollapse()" id="btn-collapse" aria-label="Minimizar plugin"
          title="Minimizar — clique no ícone para expandir novamente"
          class="p-1.5 hover:bg-light-line dark:hover:bg-dark-surface rounded-md transition-colors cursor-pointer text-slate-600 dark:text-dark-muted">
          <i data-lucide="minimize-2" class="w-4 h-4" aria-hidden="true"></i>
        </button>
      </div>
    </div>
  </header>

  <div class="flex-1 overflow-hidden relative min-h-0">
${viewHome}
${viewSpecs}
${modalsShared}
  </div>

  <!-- SIGNATURE FOOTER -->
  <footer id="footer-signature" class="pb-2 pt-1 text-center shrink-0 bg-light-surface dark:bg-dark-bg border-t border-light-line dark:border-dark-line">
    <p class="text-[9px] text-gray-400 dark:text-dark-muted font-bold tracking-wider uppercase">
      Desenvolvido por Fóton
    </p>
  </footer>

  <!--
    Plugin runtime — concatenado em um único <script> para que todos os
    módulos compartilhem o mesmo escopo. A separação em arquivos-fonte é
    puramente organizacional; o resultado em runtime é idêntico ao monolito.
  -->
  <script>
// ============================================================
// MODULE: core.js
// ============================================================
${modCore}

// ============================================================
// MODULE: messages.js
// ============================================================
${modMsgs}

// ============================================================
// GENERATED: refs/_a11y-constants.generated.js
// (fonte de verdade de A11Y_COMPONENT_PROPERTIES_GENERATED e
// A11Y_MOBILE_LINK_COMPONENT_OPTIONS_GENERATED — precisa vir ANTES de
// accessibility.js, que referencia essas constantes. Regenerar via:
// npm run refs:a11y-constants)
// ============================================================
${modA11yConstantsGenerated}

// ============================================================
// MODULE: accessibility.js
// ============================================================
${modA11y}

// ============================================================
// MODULE: onboarding.js
// ============================================================
${modOnboard}
  </script>

  <script>
    window.addEventListener('load', () => {
      if (typeof lucide !== 'undefined') lucide.createIcons();
    });
  </script>

  <div id="toast-container"></div>
  <div id="resize-handle"></div>

</body>
</html>
`;

fs.writeFileSync(OUT, html, 'utf8');
console.log(`✅ ui.html assembled (${(html.length / 1024).toFixed(1)} KB)`);
console.log(`   Source: ${BASE}`);
console.log(`   Output: ${OUT}`);
